import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 15 
padding.y = 15 

opacity = 1 
decorations = "Buttonless"
blur = true 

[font]
# normal.family = "JetBrainsMono Nerd Font Mono"
# normal.family = "FiraCode Nerd Font"
normal.family = "CaskaydiaMono Nerd Font"
size = 16.0

[mouse]
hide_when_typing = true
